import Foundation
import SwiftData

@Model
class Transaction {
    var amount: Double
    var name: String
    var type: String // "income", "expense", or "transfer"
    var timestamp: Date
    var note: String?
    
    // Identifies system-generated or recurring transactions
    var isAutoGenerated: Bool
    
    var account: Account?
    var destinationAccount: Account?
    var category: Category?
    
    init(amount: Double, name: String, type: String, timestamp: Date, isAutoGenerated: Bool = false, account: Account? = nil, destinationAccount: Account? = nil, category: Category? = nil, note: String? = nil) {
        self.amount = amount
        self.name = name
        self.type = type
        self.timestamp = timestamp
        self.isAutoGenerated = isAutoGenerated
        self.account = account
        self.destinationAccount = destinationAccount
        self.category = category
        self.note = note
    }
}
