//
//  Transaction.swift
//  MoneyTracker
//
//  Created by Alex Thuruthel on 23/06/26.
//

import Foundation
import SwiftData

@Model
final class Transaction {
    var id: UUID = UUID()
    var amount: Double
    var name: String
    var timestamp: Date
    var type: String // "expense", "income", "transfer"
    
    // Optional relationships.
    var account: Account?
    var category: Category?
    
    // Context & system tags
    var notes: String = ""
    var isAutoGenerated: Bool = false
    var isReconciliationDelta: Bool = false // Flags if this was an "Untracked Expense" fix
    
    init(amount: Double, name: String, timestamp: Date = .now, type: String, account: Account?, category: Category?, isAutoGenerated: Bool = false) {
        self.amount = amount
        self.name = name
        self.timestamp = timestamp
        self.type = type
        self.account = account
        self.category = category
        self.notes = ""
        self.isAutoGenerated = isAutoGenerated
        self.isReconciliationDelta = false
    }
}
