import SwiftUI
import SwiftData
import Charts

struct AnalyticsView: View {
    @Environment(\.modelContext) private var modelContext
    
    // Fetch user-generated transactions
    @Query(filter: #Predicate<Transaction> { $0.isAutoGenerated == false })
    private var transactions: [Transaction]
    
    // MARK: - Core Financial Logic
    
    private var totalIncome: Double {
        transactions.filter { $0.type == "income" && $0.category == nil }.reduce(0) { $0 + $1.amount }
    }
    
    private var netSpend: Double {
        let grossExpenses = transactions.filter { $0.type == "expense" }.reduce(0) { $0 + $1.amount }
        let refunds = transactions.filter { $0.type == "income" && $0.category != nil }.reduce(0) { $0 + $1.amount }
        return grossExpenses - refunds
    }
    
    private func spendForBucket(_ bucket: String) -> Double {
        let expenses = transactions.filter { $0.type == "expense" && $0.category?.masterBucket == bucket }.reduce(0) { $0 + $1.amount }
        let refunds = transactions.filter { $0.type == "income" && $0.category?.masterBucket == bucket }.reduce(0) { $0 + $1.amount }
        return max(0, expenses - refunds)
    }
    
    var body: some View {
        NavigationStack {
            List {
                // MARK: - Cash Flow Summary Hero Cards
                Section {
                    HStack(spacing: 16) {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Money In")
                                .font(.caption)
                                .fontWeight(.bold)
                                .foregroundStyle(.secondary)
                                .textCase(.uppercase)
                            Text("₹\(totalIncome.formatted())")
                                .font(.title2)
                                .fontWeight(.bold)
                                .foregroundStyle(Color.green)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        
                        Divider()
                        
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Net Spend")
                                .font(.caption)
                                .fontWeight(.bold)
                                .foregroundStyle(.secondary)
                                .textCase(.uppercase)
                            Text("₹\(netSpend.formatted())")
                                .font(.title2)
                                .fontWeight(.bold)
                                .foregroundStyle(Color.primary)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.vertical, 4)
                }
                .listRowBackground(Color(uiColor: .secondarySystemGroupedBackground))
                
                
                
                // MARK: - Drill-Down Rows (Settings Style)
                Section(header: Text("Breakdown by Bucket")) {
                    NavigationLink(destination: BucketDetailView(bucketIdentifier: "need", bucketName: "Needs", themeColor: .blue, transactions: transactions)) {
                        BucketRowLayout(title: "Needs", amount: spendForBucket("need"), color: .blue, icon: "cart.fill")
                    }
                    
                    NavigationLink(destination: BucketDetailView(bucketIdentifier: "want", bucketName: "Wants", themeColor: .purple, transactions: transactions)) {
                        BucketRowLayout(title: "Wants", amount: spendForBucket("want"), color: .purple, icon: "sparkles")
                    }
                    
                    NavigationLink(destination: BucketDetailView(bucketIdentifier: "saving", bucketName: "Savings", themeColor: .green, transactions: transactions)) {
                        BucketRowLayout(title: "Savings", amount: spendForBucket("saving"), color: .green, icon: "leaf.fill")
                    }
                }
            }
            .background(Color(uiColor: .systemGroupedBackground))
            .navigationTitle("Analytics")
        }
    }
}

// Simple row layout template to keep body hierarchy minimal
struct BucketRowLayout: View {
    let title: String
    let amount: Double
    let color: Color
    let icon: String
    
    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .frame(width: 24, height: 24)
                .foregroundStyle(color)
            
            Text(title)
                .font(.body)
                .fontWeight(.medium)
            
            Spacer()
            
            Text("₹\(amount.formatted())")
                .font(.system(.body, design: .rounded, weight: .semibold))
        }
        .padding(.vertical, 4)
    }
}
